### ISSUE TITLE
When using on Windows, it doesn't work if I use the Quick CSS for a full width titlebar.

### ISSUE THREAD

**Issue by Delta18-Git** [doggybootsy/bubblecord#3]
![image](https://user-images.githubusercontent.com/64347927/110233892-24b54180-7f4d-11eb-86e4-f4b1059f3d3a.png)

![image](https://user-images.githubusercontent.com/64347927/110233896-33035d80-7f4d-11eb-9522-85ebf8aa4225.png)

What can I do to edit this so that I can still have the full width titlebar?

**Comment by Delta18-Git** [comment]
Or, is it possible to add the full width titlebar to this theme so that Discord looks like it is a proper Windows app?

**Comment by doggybootsy** [comment]
> Or, is it possible to add the full width titlebar to this theme so that Discord looks like it is a proper Windows app?

I didnt realize how buggy the windows titlebar was so i fully deleted it
just reinstall it
