### ISSUE TITLE
Linux: Dashboard icon in server list overlaps certain elements

### ISSUE THREAD

**Issue by angelyurii** [doggybootsy/bubblecord#6]
**Describe the bug**
The Discord icon in the server list is not only attached to the main server list itself, but it overlaps most of the topmost server icon and scrolls with the actual list.

**To Reproduce**
Load the theme, and observe.

**Expected behavior**
The Discord icon should remain unscrollable and should stay in the padded area on the top of the list.

**Screenshots**
![Screenshot of issue](https://i.vgy.me/Edejh4.png)
Notice how there is still padding above the Discord logo.

**System Information**
 - OS: Void GNU/Linux x86_64
 - Kernel version: 5.10.25
 - Discord version: Latest (0.0.14)

**Additional context**
I know how to fix this -- using Developer Tools (Ctrl-Shift-I), I simply moved the Discord button's HTML element, `<div class="tutorialContainer-1v44GL">` to be the first child element of `<div class="container-2lgZY8">`. All that needs to be done from there is to adjust the padding of the background of the button. I'm unsure how to handle this myself, so that's why I'm making this an issue instead of a pull request.

**Comment by doggybootsy** [comment]
i know of this bug im fixing it. 
stable and ptb has a bug but i believe i patched it yesterday
canary changed the whole servers list

**Comment by angelyurii** [comment]
Yes, I do believe that Canary changed the server list. Haven't quite invested enough time into it quite just yet though.

Feel free to update this when you've pushed a fix :)

**Comment by doggybootsy** [comment]
> Yes, I do believe that Canary changed the server list. Haven't quite invested enough time into it quite just yet though.
> 
> Feel free to update this when you've pushed a fix :)

I believe I fixed it.

**Comment by doggybootsy** [comment]
please re open this if theres still bugs

**Comment by angelyurii** [comment]
I still seem to experience issues with the Discord icon. It's still overlapping the server icons.

**Comment by doggybootsy** [comment]
> I still seem to experience issues with the Discord icon. It's still overlapping the server icons.

Oh I'll go through it and see why it's being buggy

**Comment by angelyurii** [comment]
Thank you!

**Comment by doggybootsy** [comment]
i recently updated. i tested it on linux and it worked for me
